### PR TITLE
updated v0.22.6

### PR DESCRIPTION
**Pull request by tdejager**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

I've tried updating it to the latest version, it seemed the v0.22.1 had things that were incompatible for the mac `install` program namely using the `-D` flag. Let's see if this works.

### CODE REVIEW

**Comment by tdejager** [comment]
@conda-forge-admin, please rerender

**Comment by tdejager** [comment]
@conda-forge-admin, please rerender

**Comment by tdejager** [comment]
I don't really know about the windows build seeing as it also seems disable for the c library in the treesitter repo: https://github.com/tree-sitter/tree-sitter/blob/b40f342067a89cd6331bf4c27407588320f3c263/.github/workflows/build.yml#L137 @danielnachun wdyt?

**Comment by danielnachun** [comment]
@conda-forge-admin please rerender

**Comment by danielnachun** [comment]
I'm rerendering the feedstock now and will test on my local Windows machine if the cause of the failure isn't obvious. The CMakeLists.txt I'm using here comes from https://github.com/neovim/neovim/blob/master/cmake.deps/cmake/TreesitterCMakeLists.txt, which doesn't seem to have changed much.

**Comment by danielnachun** [comment]
And of course the one line that did change in the CMakeLists.txt was the one that mattered.  The `parser.h` file has been moved from the `include`, presumably because its exports are supposed to be accessed through `api.h`.

**Pull request merged**
